# Generated by Django 4.0.3 on 2022-03-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_producto_colores_producto_estado_producto_notas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='notas',
        ),
    ]
