# Generated by Django 4.0.3 on 2022-04-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0003_remove_producto_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadProducto', models.IntegerField(null=True, verbose_name='Cantidad de productos')),
                ('precioTotal', models.IntegerField(null=True, verbose_name='Precio total')),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='Nombre')),
                ('celular', models.IntegerField(null=True, verbose_name='Celular')),
                ('datosProducto', models.TextField(null=True, verbose_name='Datos del producto')),
            ],
        ),
    ]
