# Generated by Django 4.0.3 on 2022-04-06 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0004_pedidos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
    ]
