# Generated by Django 4.0.3 on 2022-04-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0005_rename_pedidos_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.CharField(max_length=60, null=True, verbose_name='Fecha'),
        ),
    ]
