# Generated by Django 4.0.3 on 2022-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0007_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='Nuevo', max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
