# Generated by Django 4.0.3 on 2022-05-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0009_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precioTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Total'),
        ),
    ]
