# Generated by Django 4.0.3 on 2022-05-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0010_alter_pedido_preciototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Nuevos', max_length=20, verbose_name='Categoría'),
        ),
    ]
