# Generated by Django 4.0.3 on 2022-05-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0011_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='celular',
            field=models.CharField(max_length=10, null=True, verbose_name='Celular'),
        ),
    ]
