# Generated by Django 4.0.3 on 2022-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0013_cuentas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costos')),
                ('fecha', models.CharField(max_length=60, null=True, verbose_name='Fecha')),
                ('detalles', models.TextField(null=True, verbose_name='Detalles')),
            ],
        ),
        migrations.DeleteModel(
            name='Cuentas',
        ),
    ]
